In [1]:
import numpy as np

In [13]:
b = np.array([[1,1,1],[2,2,2]])

In [15]:
b.shape

# Shape Shows The Dimenstion of Array or About Rows and Colums
# (Row,Colums)

(2, 3)

In [16]:
b.dtype
# dtype Function Shows Which Type Of Data Store in Array

dtype('int32')

In [18]:
b.ndim

# ndim Function Shows How Many Rows resent In Numpy Srray

2

In [19]:
print(type(b))

<class 'numpy.ndarray'>


In [25]:
# What Happen When We Want A Numpy Arrayfrom 1 to 20?
# It Will Create A Numpy array from 0 to 20-1
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
c = range(10000)

In [27]:
%timeit {i**3 for i in c}

6.73 ms ± 696 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [29]:
c_numpy = np.arange(10000)

In [30]:
%timeit c_numpy**3

26.8 µs ± 880 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [31]:
# Explanation :  %timeit Function Use To calculate The Time of Running A loop or Process,
#                normal array/list take more execution time compair numpy_array


In [33]:
np.arange(1,12,2)
# exp. np.arrange(start,end,diffrenceB/W)

array([ 1,  3,  5,  7,  9, 11])

In [34]:
np.zeros((3,2))
# Return 3 rows and 2 colume with 0's Elemtnt same as Once As well

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.full((3,5),9)
# full function create matrix with same Value What we Pass

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [40]:
# Getting Random Value From Zero to One
np.random.random()

0.07196769336591025

In [41]:
a = np.linspace(1,50,100)
# linspace Function  Create The numpy Arr. from 1 to 50 but it Will equally Divided into in 100 Parts

In [42]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [44]:
a.itemsize
# itemsize Calculate The Amount Of Memory been used to do a task  


8

In [56]:
# Lets Create 1 nd numpy Array
arr = np.arange(18)
arr.shape
arr.reshape(2,3,3);
# Converting 18 to 2*3*3 = 18 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [68]:
q =np.array([[1,2,3],[4,5,6],[7,8,9]])
q[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
q>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [73]:
sinn = np.arange(10)
np.sin(sinn)
# Get Sin value

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [74]:
np.cos(sinn)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [75]:
np.exp(sinn)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [76]:
np.sum(sinn)

45

In [77]:
np.median(sinn)

4.5

In [78]:
np.std(sinn)

2.8722813232690143

In [81]:
newArray = np.arange(1,10).reshape(3,3)
newArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
# Calulate Determinant of newArray
np.linalg.det(newArray)

-9.51619735392994e-16

In [86]:
np.linalg.inv(newArray)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [87]:
np.linalg.eig(newArray)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))