In [15]:


import numpy as np 
a = np.array([1,2,3,4,5])
a= a+1;
a

# NOTE     one Can Added To Each Element in  array 



array([2, 3, 4, 5, 6])

In [17]:
a**2

array([ 4,  9, 16, 25, 36], dtype=int32)

In [39]:
b= np.array([3,4,5,6,7])
b=b+1
# b-a
# b*a
# b+a
b/a
# Here All Operation Willl Be performed 


array([2.        , 1.66666667, 1.5       , 1.4       , 1.33333333])

In [41]:
#  Examp Of Diagonal Matrix \
#  np.diag([a,s,v,v])=> Will Give Diagonal matrix on 

a= np.diag([1,2,3,4,5,6,78,9])
a

array([[ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 78,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  9]])

In [44]:
# Arraty Equal  =  Return true or False wherther Array Are samne Or Not 

a= np.array([1,2,3,4,5])
b= np.array([1,2,3,4,5])
c= np.array([22,5,6,5])

np.array_equal(a,b)


True

# LOGICAL OPERAATOR 

In [52]:
#  To Get The Sin Theta All Value 
sinArray = np.array([0,1,2,3,4,5])
# np.sin(sinArray)
# np.log(sinArray)
np.exp(sinArray)


#  NOTE These three Are Working Correctlly 


array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [67]:
# NOTE:  it Will Comute All The Loop With Writing Code 

arangeList = np.arange(10)
np.sum(arangeList)


#  Muyltidimestional Array   

mulDim = np.array([[1,1,1],[2,2,2]])

#  For Addition or ROWWISE
mulDim.sum(axis = 1)

#  For Addition or Colum Wise
mulDim.sum(axis = 0)




array([3, 6])

In [70]:
#  argMax and Arg Min function
# argmin = Used To Get smallest value and return Indes
# x

argMin = np.array([2,3,4,5,1,7,8,9])
argMin.argmin()
argMin.argmax()



7

In [83]:
# STATICS FUNCTION
meanArra1 = np.array([1,1,1])
# meanArra1.mean()
np.median(meanArra1)
# np.mean(meanArra1)






1.0

In [1]:
import numpy as np 
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a = np.ones((4,7), dtype = np.int16)
a

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [9]:
b = np.arange([1,3,5,3,6,3,8,6,7,8])
b

TypeError: unsupported operand type(s) for -: 'list' and 'int'